# SRC += features/achordion.c

VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes

BOOTMAGIC_ENABLE = no
REPEAT_KEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = yes
BACKLIGHT_ENABLE = no
MIDI_ENABLE = no
AUDIO_ENABLE = no
BLUETOOTH_ENABLE = no
RGBLIGHT_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
AUTOCORRECT_ENABLE = no
CAPS_WORD_ENABLE = yes

SPLIT_KEYBOARD = yes
