SRC += features/achordion.c

VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes

AUDIO_ENABLE = no
BACKLIGHT_ENABLE = no
BLUETOOTH_ENABLE = no
BOOTMAGIC_ENABLE = no
COMBO_ENABLE = yes
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
GRAVE_ESC_ENABLE = no
MIDI_ENABLE = no
MOUSEKEY_ENABLE = no
RGBLIGHT_ENABLE = no
SPACE_CADET_ENABLE = no
TAP_DANCE_ENABLE = no

AUTOCORRECT_ENABLE = no
CAPS_WORD_ENABLE = yes
REPEAT_KEY_ENABLE = yes

SPLIT_KEYBOARD = yes
